basePath: /
info:
  contact:
    email: 584807419@qq.com
    name: 联系人
    url: http://www.swagger.io/support
  description: 字节青训营-模仿抖音项目
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: mock tiktok
  version: 1.0 版本
paths:
  /douyin/relation/action:
    post:
      consumes:
      - application/json
      description: 关注或者取消关注用户
      parameters:
      - description: 关注者
        in: query
        name: user_id
        required: true
        type: integer
      - description: 被关注者
        in: query
        name: to_user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: 参数不正确
          schema:
            type: body
        "403":
          description: 未登录
          schema:
            type: body
        "500":
          description: 系统错误
          schema:
            type: body
      summary: 关注操作
      tags:
      - Relation
  /douyin/relation/follow/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 关注列表
      tags:
      - Relation
  /douyin/relation/follower/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 粉丝列表
      tags:
      - Relation
  /douyin/relation/friend/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 好友列表
      tags:
      - Message
swagger: "2.0"
